---
title: "PAD Odissa"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: yeti
params:
  datapath: "data/combined_outcomes.csv"
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
source("ReadDataApp.R")
source("modified_thompson.R")
#source("optimal_stopping.R")
```

```{r, message=F, echo=F, warning=F}
k=6
control_treatment=1
treatment_names = c(
  "no SMS, 10am",
  "SMS 1h before, 10am",
  "SMS 24h before, 10am",
  "no SMS, 6:30pm",
  "SMS 1h before, 6:30pm",
  "SMS 24h before, 6:30 pm"
)



priordata=ReadDataApp(params$datapath)
```

# Summary statistics


Column 1
--------------------------------------------------



### Number of observations 


`r valueBox(length(priordata$Y))`

### Success rate
`r gauge(round(mean(priordata$Y), digits=2), min=0, max=1)`




### Success rate by treatment

```{r, message=F, echo=F, cache=F, fig.width=6, fig.height=3}
by_treatment= as_tibble(priordata[c("Y","D")]) %>% 
  group_by(D, .drop=FALSE) %>% 
  summarise(avg=mean(Y), count=n(), successes=sum(Y)) %>% 
  mutate(treatment=factor(treatment_names, levels=treatment_names))


ggplot(by_treatment, aes(x=treatment, y=avg, color = treatment)) +
    geom_point(size=5) +
    scale_color_viridis_d() +
    coord_flip() +
    ylim(0, NA) +
    theme_minimal()+
    theme(legend.position = "none")
```                    


Column 2
--------------------------------------------------



### Past distribution across treatments

```{r, message=F, echo=F, cache=F, fig.width=6, fig.height=3}
ggplot(by_treatment, aes(x=treatment, y=count, fill=treatment)) +
    geom_col() +
    scale_fill_viridis_d() +
    coord_flip() +
    theme_minimal() +
    theme(legend.position = "none") +
    labs(x="Treatment", y="Number of observations")

ggsave("figures_for_export/assignment_shares.pdf", width=6, height=2)
```



### Current assignment probabilities

```{r, echo=F, fig.width=6, fig.height=3}
P_current = DtchoiceThompson_modified(
  priordata$Y,
  priordata$D,
  priordata$k,
  Nt = Nt,
  return_probabilities = T
)

#knitr::kable(P_current, digits=2)
P_current_tibble = tibble(share = as_vector(P_current),
                          treatment = factor(treatment_names, levels = treatment_names))

ggplot(P_current_tibble, aes(x = treatment, y = share, fill = treatment)) +
  geom_col() +
  scale_fill_viridis_d() +
  coord_flip() +
  theme_minimal() +
  theme(legend.position = "none")
```


# Time series

```{r}
by_date= read_csv(params$datapath) %>% 
    mutate(date=mdy(date),
           treatment = factor(treatment, labels = treatment_names)) 

frequency_series = by_date %>% 
    group_by(date, treatment) %>% 
    summarise(n=n()) 

series_labels = frequency_series %>% 
    filter(date==max(frequency_series$date))
```


### Success rate over time

```{r, fig.width=10, fig.height=3}
by_date %>% 
    group_by(date) %>% 
    summarise(avg=mean(outcome)) %>% 
ggplot(aes(x=date, y=avg)) +
    #geom_point() +
    geom_line(size=2) +
    scale_y_continuous(limits = c(0,.3), breaks=seq(0,.3,.05)) +
    scale_x_date(limits=c(min(frequency_series$date),max(frequency_series$date)+3),
                 breaks=ymd(unique(frequency_series$date)),
                 date_labels = "%b %d") +
    labs(x="Date", y="Success rate") +
    theme_minimal()
```

### Assignment frequencies over time

```{r, fig.width=10, fig.height=3 }


frequency_series %>% 
ggplot(aes(x=date, y=n, color=treatment)) +
    #geom_point(size=3) +
    geom_line(size=1) +
    #ggrepel::geom_label_repel(data= series_labels, aes(y=n, label=treatment), direction="y", hjust=0, size=3) +
    scale_y_continuous(limits = c(0,300), breaks=seq(0,300,50),
                       sec.axis = dup_axis(name=NULL, breaks=series_labels$n, labels=series_labels$treatment)
                       ) +
    scale_x_date(limits=c(min(frequency_series$date),max(frequency_series$date)),expand=expand_scale(mult=0),
                 breaks=ymd(unique(frequency_series$date)),
                 date_labels = "%b %d") +
    scale_color_viridis_d() +
    labs(x="Date", y="Number of observations") +
    theme_minimal() +
    theme(legend.position = "none")

ggsave("figures_for_export/assignment_shares_timeseries.pdf", width=8, height=3)
```

# Tables

## Column 1

### Tabulated data

```{r}
tabulation=by_treatment %>% 
  select(treatment, count, successes, avg)
colnames(tabulation)=c("Treatment", "Obervations", "Successes", "Share of successes")

tabulation %>% 
  knitr::kable(row.names=F, digits = c(NA,0,0,2))

print(
    xtable::xtable(
        tabulation,
        type = "latex",
        caption = "Tabulated data",
        label = paste("tab:tabulated"),
        digits = c(NA, NA, 0, 0, 2),
    ),
    file = "./figures_for_export/tabulated_PAD.tex",
    caption.placement = "top",
    latex.environments = "center",
    include.rownames = FALSE,
)    
```

## Column 2

### Posterior parameters

```{r}
P_optimal = DtchoiceThompsonProbabilities(
  priordata$Y,
  priordata$D,
  priordata$k
) %>% as_vector

Bayes_table=by_treatment %>% 
  mutate(alpha= 1 + successes,
         beta= 1 + count-successes,
         mean = alpha / (alpha+beta),
         var = alpha * beta / ((alpha+beta)^2 * (alpha+beta +1)  ),
         std = sqrt(var),
         succ_proba = P_optimal) %>% 
  select(treatment, mean, std, succ_proba) 

colnames(Bayes_table)=c("Treatment", "Mean", "Standard dev", "Probability optimal")

Bayes_table %>% 
  knitr::kable(row.names=F, digits = c(NA,3,3,3))

print(
    xtable::xtable(
        Bayes_table,
        type = "latex",
        caption = "Posterior parameters",
        label = paste("tab:posterior"),
        digits = c(NA, NA, 3,3,3)
    ),
    file = "./figures_for_export/posterior_PAD.tex",
    caption.placement = "top",
    latex.environments = "center",
    include.rownames = FALSE,
)    
```

# Source data



`r read_csv(params$datapath) %>%
  knitr::kable(row.names=F)`

